// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AgentRun struct {
	ID     string       `json:"id"`
	TripID *string      `json:"tripId,omitempty"`
	Status AgentStatus  `json:"status"`
	Steps  []*AgentStep `json:"steps"`
}

type AgentStep struct {
	Name          string      `json:"name"`
	Status        AgentStatus `json:"status"`
	DurationMs    int         `json:"durationMs"`
	InputSummary  *string     `json:"inputSummary,omitempty"`
	OutputSummary *string     `json:"outputSummary,omitempty"`
	Retries       int         `json:"retries"`
	Error         *string     `json:"error,omitempty"`
}

type ConnectivityGuide struct {
	BeforeDeparture []string `json:"beforeDeparture"`
	AirportSetup    []string `json:"airportSetup"`
	OfflineStrategy []string `json:"offlineStrategy"`
	BackupInternet  []string `json:"backupInternet"`
	EmergencyAccess []string `json:"emergencyAccess"`
}

type Mutation struct {
}

type PlanOption struct {
	ID           string  `json:"id"`
	Provider     string  `json:"provider"`
	Name         string  `json:"name"`
	PriceUsd     float64 `json:"priceUsd"`
	DataGb       float64 `json:"dataGb"`
	ValidityDays int     `json:"validityDays"`
	Tradeoff     string  `json:"tradeoff"`
}

type Query struct {
}

type Trip struct {
	ID            string       `json:"id"`
	Destination   string       `json:"destination"`
	StartDate     string       `json:"startDate"`
	EndDate       string       `json:"endDate"`
	TravelerType  TravelerType `json:"travelerType"`
	EstimatedGb   *float64     `json:"estimatedGb,omitempty"`
	RecommendedGb *float64     `json:"recommendedGb,omitempty"`
}

type TripAnalysis struct {
	TripID            string             `json:"tripId"`
	AgentRunID        string             `json:"agentRunId"`
	EstimatedGb       float64            `json:"estimatedGb"`
	RecommendedGb     float64            `json:"recommendedGb"`
	Confidence        float64            `json:"confidence"`
	UsageBreakdown    *UsageBreakdown    `json:"usageBreakdown"`
	SelectedPlan      *PlanOption        `json:"selectedPlan"`
	Recommendation    string             `json:"recommendation"`
	Alternatives      []*PlanOption      `json:"alternatives"`
	ConnectivityGuide *ConnectivityGuide `json:"connectivityGuide,omitempty"`
	AgentSteps        []*AgentStep       `json:"agentSteps"`
}

type TripInput struct {
	Destination  string       `json:"destination"`
	StartDate    string       `json:"startDate"`
	EndDate      string       `json:"endDate"`
	TravelerType TravelerType `json:"travelerType"`
	BudgetUsd    *float64     `json:"budgetUsd,omitempty"`
	Usage        *UsageInput  `json:"usage"`
	SessionID    *string      `json:"sessionId,omitempty"`
}

type UsageBreakdown struct {
	Maps        float64 `json:"maps"`
	Streaming   float64 `json:"streaming"`
	SocialMedia float64 `json:"socialMedia"`
	VideoCalls  float64 `json:"videoCalls"`
	Hotspot     float64 `json:"hotspot"`
	Work        float64 `json:"work"`
}

type UsageInput struct {
	Streaming   UsageLevel `json:"streaming"`
	VideoCalls  UsageLevel `json:"videoCalls"`
	Hotspot     UsageLevel `json:"hotspot"`
	Maps        UsageLevel `json:"maps"`
	SocialMedia UsageLevel `json:"socialMedia"`
	Work        UsageLevel `json:"work"`
}

type AgentStatus string

const (
	AgentStatusPending   AgentStatus = "PENDING"
	AgentStatusRunning   AgentStatus = "RUNNING"
	AgentStatusCompleted AgentStatus = "COMPLETED"
	AgentStatusFailed    AgentStatus = "FAILED"
	AgentStatusSkipped   AgentStatus = "SKIPPED"
)

var AllAgentStatus = []AgentStatus{
	AgentStatusPending,
	AgentStatusRunning,
	AgentStatusCompleted,
	AgentStatusFailed,
	AgentStatusSkipped,
}

func (e AgentStatus) IsValid() bool {
	switch e {
	case AgentStatusPending, AgentStatusRunning, AgentStatusCompleted, AgentStatusFailed, AgentStatusSkipped:
		return true
	}
	return false
}

func (e AgentStatus) String() string {
	return string(e)
}

func (e *AgentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentStatus", str)
	}
	return nil
}

func (e AgentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TravelerType string

const (
	TravelerTypeSolo     TravelerType = "SOLO"
	TravelerTypeCouple   TravelerType = "COUPLE"
	TravelerTypeFamily   TravelerType = "FAMILY"
	TravelerTypeBusiness TravelerType = "BUSINESS"
)

var AllTravelerType = []TravelerType{
	TravelerTypeSolo,
	TravelerTypeCouple,
	TravelerTypeFamily,
	TravelerTypeBusiness,
}

func (e TravelerType) IsValid() bool {
	switch e {
	case TravelerTypeSolo, TravelerTypeCouple, TravelerTypeFamily, TravelerTypeBusiness:
		return true
	}
	return false
}

func (e TravelerType) String() string {
	return string(e)
}

func (e *TravelerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TravelerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TravelerType", str)
	}
	return nil
}

func (e TravelerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TravelerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TravelerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UsageLevel string

const (
	UsageLevelNone     UsageLevel = "NONE"
	UsageLevelLight    UsageLevel = "LIGHT"
	UsageLevelModerate UsageLevel = "MODERATE"
	UsageLevelHeavy    UsageLevel = "HEAVY"
)

var AllUsageLevel = []UsageLevel{
	UsageLevelNone,
	UsageLevelLight,
	UsageLevelModerate,
	UsageLevelHeavy,
}

func (e UsageLevel) IsValid() bool {
	switch e {
	case UsageLevelNone, UsageLevelLight, UsageLevelModerate, UsageLevelHeavy:
		return true
	}
	return false
}

func (e UsageLevel) String() string {
	return string(e)
}

func (e *UsageLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UsageLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UsageLevel", str)
	}
	return nil
}

func (e UsageLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UsageLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UsageLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
