package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"time"

	"github.com/connecta/connecta/backend/graph/generated"
	"github.com/connecta/connecta/backend/graph/models"
	"github.com/connecta/connecta/backend/internal/domain"
)

// AnalyzeTrip is the resolver for the analyzeTrip field.
func (r *mutationResolver) AnalyzeTrip(ctx context.Context, input models.TripInput) (*models.TripAnalysis, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	tripInput, err := toDomainTripInput(input)
	if err != nil {
		return nil, err
	}

	analysis, err := r.TripService.AnalyzeTrip(ctx, tripInput)
	if err != nil {
		return nil, err
	}
	return toGraphTripAnalysis(analysis), nil
}

// Trips is the resolver for the trips field.
func (r *queryResolver) Trips(ctx context.Context) ([]*models.Trip, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	analyses, err := r.TripService.ListTrips(ctx)
	if err != nil {
		return nil, err
	}

	trips := make([]*models.Trip, 0, len(analyses))
	for _, analysis := range analyses {
		trips = append(trips, toGraphTrip(analysis))
	}
	return trips, nil
}

// Trip is the resolver for the trip field.
func (r *queryResolver) Trip(ctx context.Context, id string) (*models.Trip, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	analysis, ok, err := r.TripService.GetAnalysis(ctx, id)
	if err != nil || !ok {
		return nil, err
	}
	return toGraphTrip(analysis), nil
}

// AgentRun is the resolver for the agentRun field.
func (r *queryResolver) AgentRun(ctx context.Context, id string) (*models.AgentRun, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	analyses, err := r.TripService.ListTrips(ctx)
	if err != nil {
		return nil, err
	}
	for _, analysis := range analyses {
		if analysis.AgentRunID == id {
			return toGraphAgentRun(analysis), nil
		}
	}
	return nil, nil
}

// TripsBySession is the resolver for the tripsBySession field.
func (r *queryResolver) TripsBySession(ctx context.Context, sessionID string) ([]*models.Trip, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	analyses, err := r.TripService.GetBySession(ctx, sessionID)
	if err != nil {
		return nil, err
	}

	trips := make([]*models.Trip, 0, len(analyses))
	for _, analysis := range analyses {
		trips = append(trips, toGraphTrip(analysis))
	}
	return trips, nil
}

// TripUsage is the resolver for the tripUsage field.
func (r *queryResolver) TripUsage(ctx context.Context, tripID string) ([]*models.UsageSnapshot, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	snapshots, err := r.TripService.GetUsageByTrip(ctx, tripID)
	if err != nil {
		return nil, err
	}
	return toGraphUsageSnapshots(snapshots), nil
}

// ConfirmTrip is the resolver for the confirmTrip field.
func (r *mutationResolver) ConfirmTrip(ctx context.Context, input models.ConfirmTripInput) (*models.Trip, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	domainInput, err := toDomainConfirmTripInput(input)
	if err != nil {
		return nil, err
	}

	analysis, err := r.TripService.ConfirmTrip(ctx, domainInput)
	if err != nil {
		return nil, err
	}
	return toGraphTrip(analysis), nil
}

// SubmitUsageSnapshot is the resolver for the submitUsageSnapshot field.
func (r *mutationResolver) SubmitUsageSnapshot(ctx context.Context, input models.SubmitUsageSnapshotInput) (*models.UsageSnapshot, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	saved, err := r.TripService.SubmitUsageSnapshot(ctx, domain.UsageSnapshot{
		TripID:      input.TripID,
		DataUsedMB:  input.DataUsedMb,
		BatteryPct:  input.BatteryPct,
		NetworkType: input.NetworkType,
	})
	if err != nil {
		return nil, err
	}
	return toGraphUsageSnapshot(saved), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func toDomainTripInput(input models.TripInput) (domain.TripInput, error) {
	startDate, err := time.Parse("2006-01-02", input.StartDate)
	if err != nil {
		return domain.TripInput{}, errors.New("startDate must use YYYY-MM-DD")
	}
	endDate, err := time.Parse("2006-01-02", input.EndDate)
	if err != nil {
		return domain.TripInput{}, errors.New("endDate must use YYYY-MM-DD")
	}
	if input.Usage == nil {
		return domain.TripInput{}, errors.New("usage is required")
	}

	return domain.TripInput{
		Destination:  input.Destination,
		StartDate:    startDate,
		EndDate:      endDate,
		TravelerType: domain.TravelerType(input.TravelerType),
		BudgetUSD:    input.BudgetUsd,
		SessionID:    input.SessionID,
		Usage: domain.UsageProfile{
			Streaming:   domain.UsageLevel(input.Usage.Streaming),
			VideoCalls:  domain.UsageLevel(input.Usage.VideoCalls),
			Hotspot:     domain.UsageLevel(input.Usage.Hotspot),
			Maps:        domain.UsageLevel(input.Usage.Maps),
			SocialMedia: domain.UsageLevel(input.Usage.SocialMedia),
			Work:        domain.UsageLevel(input.Usage.Work),
		},
	}, nil
}

func toGraphTripAnalysis(analysis domain.TripAnalysis) *models.TripAnalysis {
	return &models.TripAnalysis{
		TripID:        analysis.TripID,
		AgentRunID:    analysis.AgentRunID,
		EstimatedGb:   analysis.Estimate.EstimatedGB,
		RecommendedGb: analysis.Estimate.RecommendedGB,
		Confidence:    analysis.Estimate.Confidence,
		UsageBreakdown: &models.UsageBreakdown{
			Maps:        analysis.Estimate.Breakdown.Maps,
			Streaming:   analysis.Estimate.Breakdown.Streaming,
			SocialMedia: analysis.Estimate.Breakdown.SocialMedia,
			VideoCalls:  analysis.Estimate.Breakdown.VideoCalls,
			Hotspot:     analysis.Estimate.Breakdown.Hotspot,
			Work:        analysis.Estimate.Breakdown.Work,
		},
		SelectedPlan:      toGraphPlanOption(analysis.SelectedPlan),
		Recommendation:    analysis.Recommendation,
		Alternatives:      toGraphPlanOptions(analysis.Alternatives),
		ConnectivityGuide: toGraphConnectivityGuide(analysis.ConnectivityGuide),
		AgentSteps:        toGraphAgentSteps(analysis.AgentSteps),
	}
}

func toGraphTrip(analysis domain.TripAnalysis) *models.Trip {
	estimated := analysis.Estimate.EstimatedGB
	recommended := analysis.Estimate.RecommendedGB
	trip := &models.Trip{
		ID:            analysis.TripID,
		Destination:   analysis.Destination,
		StartDate:     analysis.StartDate.Format("2006-01-02"),
		EndDate:       analysis.EndDate.Format("2006-01-02"),
		TravelerType:  models.TravelerType(analysis.TravelerType),
		EstimatedGb:   &estimated,
		RecommendedGb: &recommended,
	}

	if analysis.SelectedPlan.Name != "" {
		trip.SelectedPlan = toGraphPlanOption(analysis.SelectedPlan)
	}

	if analysis.ConfirmedAt != nil {
		confirmedAt := analysis.ConfirmedAt.Format(time.RFC3339)
		trip.ConfirmedAt = &confirmedAt
	}
	if analysis.ConfirmedPlan != nil {
		trip.ConfirmedPlan = &models.ConfirmedPlan{
			Provider:     analysis.ConfirmedPlan.Provider,
			Name:         analysis.ConfirmedPlan.Name,
			PriceUsd:     analysis.ConfirmedPlan.PriceUSD,
			DataLabel:    analysis.ConfirmedPlan.DataLabel,
			ValidityDays: analysis.ConfirmedPlan.ValidityDays,
		}
	}

	return trip
}

func toDomainConfirmTripInput(input models.ConfirmTripInput) (domain.ConfirmTripInput, error) {
	result := domain.ConfirmTripInput{
		TripID:      input.TripID,
		SessionID:   input.SessionID,
		Destination: input.Destination,
		Plan: domain.ConfirmedPlan{
			Provider:     input.Plan.Provider,
			Name:         input.Plan.Name,
			PriceUSD:     input.Plan.PriceUsd,
			DataLabel:    input.Plan.DataLabel,
			ValidityDays: input.Plan.ValidityDays,
		},
	}

	if input.StartDate != nil {
		startDate, err := time.Parse("2006-01-02", *input.StartDate)
		if err != nil {
			return domain.ConfirmTripInput{}, errors.New("startDate must use YYYY-MM-DD")
		}
		result.StartDate = &startDate
	}
	if input.EndDate != nil {
		endDate, err := time.Parse("2006-01-02", *input.EndDate)
		if err != nil {
			return domain.ConfirmTripInput{}, errors.New("endDate must use YYYY-MM-DD")
		}
		result.EndDate = &endDate
	}
	if input.TravelerType != nil {
		travelerType := domain.TravelerType(*input.TravelerType)
		result.TravelerType = &travelerType
	}

	return result, nil
}

func toGraphUsageSnapshot(snapshot domain.UsageSnapshot) *models.UsageSnapshot {
	return &models.UsageSnapshot{
		ID:          snapshot.ID,
		TripID:      snapshot.TripID,
		DataUsedMb:  snapshot.DataUsedMB,
		BatteryPct:  snapshot.BatteryPct,
		NetworkType: snapshot.NetworkType,
		CapturedAt:  snapshot.CapturedAt.Format(time.RFC3339),
	}
}

func toGraphUsageSnapshots(snapshots []domain.UsageSnapshot) []*models.UsageSnapshot {
	result := make([]*models.UsageSnapshot, 0, len(snapshots))
	for _, snapshot := range snapshots {
		result = append(result, toGraphUsageSnapshot(snapshot))
	}
	return result
}

func toGraphAgentRun(analysis domain.TripAnalysis) *models.AgentRun {
	return &models.AgentRun{
		ID:     analysis.AgentRunID,
		TripID: &analysis.TripID,
		Status: models.AgentStatusCompleted,
		Steps:  toGraphAgentSteps(analysis.AgentSteps),
	}
}

func toGraphPlanOption(plan domain.PlanOption) *models.PlanOption {
	return &models.PlanOption{
		ID:           plan.ID,
		Provider:     plan.Provider,
		Name:         plan.Name,
		PriceUsd:     plan.PriceUSD,
		DataGb:       plan.DataGB,
		ValidityDays: plan.ValidityDays,
		Tradeoff:     plan.Tradeoff,
	}
}

func toGraphPlanOptions(plans []domain.PlanOption) []*models.PlanOption {
	result := make([]*models.PlanOption, 0, len(plans))
	for _, plan := range plans {
		result = append(result, toGraphPlanOption(plan))
	}
	return result
}

func toGraphConnectivityGuide(guide *domain.ConnectivityGuide) *models.ConnectivityGuide {
	if guide == nil {
		return nil
	}
	return &models.ConnectivityGuide{
		BeforeDeparture: guide.BeforeDeparture,
		AirportSetup:    guide.AirportSetup,
		OfflineStrategy: guide.OfflineStrategy,
		BackupInternet:  guide.BackupInternet,
		EmergencyAccess: guide.EmergencyAccess,
	}
}

func toGraphAgentSteps(steps []domain.AgentStep) []*models.AgentStep {
	result := make([]*models.AgentStep, 0, len(steps))
	for _, step := range steps {
		result = append(result, &models.AgentStep{
			Name:          step.Name,
			Status:        models.AgentStatus(step.Status),
			DurationMs:    step.DurationMS,
			InputSummary:  step.InputSummary,
			OutputSummary: step.OutputSummary,
			Retries:       step.Retries,
			Error:         step.Error,
		})
	}
	return result
}
