package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"time"

	"github.com/connecta/connecta/backend/graph/generated"
	"github.com/connecta/connecta/backend/graph/models"
	"github.com/connecta/connecta/backend/internal/domain"
)

// AnalyzeTrip is the resolver for the analyzeTrip field.
func (r *mutationResolver) AnalyzeTrip(ctx context.Context, input models.TripInput) (*models.TripAnalysis, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	tripInput, err := toDomainTripInput(input)
	if err != nil {
		return nil, err
	}

	analysis, err := r.TripService.AnalyzeTrip(ctx, tripInput)
	if err != nil {
		return nil, err
	}
	return toGraphTripAnalysis(analysis), nil
}

// Trips is the resolver for the trips field.
func (r *queryResolver) Trips(ctx context.Context) ([]*models.Trip, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	analyses, err := r.TripService.ListTrips(ctx)
	if err != nil {
		return nil, err
	}

	trips := make([]*models.Trip, 0, len(analyses))
	for _, analysis := range analyses {
		trips = append(trips, toGraphTrip(analysis))
	}
	return trips, nil
}

// Trip is the resolver for the trip field.
func (r *queryResolver) Trip(ctx context.Context, id string) (*models.Trip, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	analysis, ok, err := r.TripService.GetAnalysis(ctx, id)
	if err != nil || !ok {
		return nil, err
	}
	return toGraphTrip(analysis), nil
}

// AgentRun is the resolver for the agentRun field.
func (r *queryResolver) AgentRun(ctx context.Context, id string) (*models.AgentRun, error) {
	if r.TripService == nil {
		return nil, errors.New("trip service is not configured")
	}

	analyses, err := r.TripService.ListTrips(ctx)
	if err != nil {
		return nil, err
	}
	for _, analysis := range analyses {
		if analysis.AgentRunID == id {
			return toGraphAgentRun(analysis), nil
		}
	}
	return nil, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func toDomainTripInput(input models.TripInput) (domain.TripInput, error) {
	startDate, err := time.Parse("2006-01-02", input.StartDate)
	if err != nil {
		return domain.TripInput{}, errors.New("startDate must use YYYY-MM-DD")
	}
	endDate, err := time.Parse("2006-01-02", input.EndDate)
	if err != nil {
		return domain.TripInput{}, errors.New("endDate must use YYYY-MM-DD")
	}
	if input.Usage == nil {
		return domain.TripInput{}, errors.New("usage is required")
	}

	return domain.TripInput{
		Destination:  input.Destination,
		StartDate:    startDate,
		EndDate:      endDate,
		TravelerType: domain.TravelerType(input.TravelerType),
		BudgetUSD:    input.BudgetUsd,
		Usage: domain.UsageProfile{
			Streaming:   domain.UsageLevel(input.Usage.Streaming),
			VideoCalls:  domain.UsageLevel(input.Usage.VideoCalls),
			Hotspot:     domain.UsageLevel(input.Usage.Hotspot),
			Maps:        domain.UsageLevel(input.Usage.Maps),
			SocialMedia: domain.UsageLevel(input.Usage.SocialMedia),
			Work:        domain.UsageLevel(input.Usage.Work),
		},
	}, nil
}

func toGraphTripAnalysis(analysis domain.TripAnalysis) *models.TripAnalysis {
	return &models.TripAnalysis{
		TripID:        analysis.TripID,
		AgentRunID:    analysis.AgentRunID,
		EstimatedGb:   analysis.Estimate.EstimatedGB,
		RecommendedGb: analysis.Estimate.RecommendedGB,
		Confidence:    analysis.Estimate.Confidence,
		UsageBreakdown: &models.UsageBreakdown{
			Maps:        analysis.Estimate.Breakdown.Maps,
			Streaming:   analysis.Estimate.Breakdown.Streaming,
			SocialMedia: analysis.Estimate.Breakdown.SocialMedia,
			VideoCalls:  analysis.Estimate.Breakdown.VideoCalls,
			Hotspot:     analysis.Estimate.Breakdown.Hotspot,
			Work:        analysis.Estimate.Breakdown.Work,
		},
		SelectedPlan:      toGraphPlanOption(analysis.SelectedPlan),
		Recommendation:    analysis.Recommendation,
		Alternatives:      toGraphPlanOptions(analysis.Alternatives),
		ConnectivityGuide: toGraphConnectivityGuide(analysis.ConnectivityGuide),
		AgentSteps:        toGraphAgentSteps(analysis.AgentSteps),
	}
}

func toGraphTrip(analysis domain.TripAnalysis) *models.Trip {
	estimated := analysis.Estimate.EstimatedGB
	recommended := analysis.Estimate.RecommendedGB
	return &models.Trip{
		ID:            analysis.TripID,
		Destination:   analysis.Destination,
		StartDate:     analysis.StartDate.Format("2006-01-02"),
		EndDate:       analysis.EndDate.Format("2006-01-02"),
		TravelerType:  models.TravelerType(analysis.TravelerType),
		EstimatedGb:   &estimated,
		RecommendedGb: &recommended,
	}
}

func toGraphAgentRun(analysis domain.TripAnalysis) *models.AgentRun {
	return &models.AgentRun{
		ID:     analysis.AgentRunID,
		TripID: &analysis.TripID,
		Status: models.AgentStatusCompleted,
		Steps:  toGraphAgentSteps(analysis.AgentSteps),
	}
}

func toGraphPlanOption(plan domain.PlanOption) *models.PlanOption {
	return &models.PlanOption{
		ID:           plan.ID,
		Provider:     plan.Provider,
		Name:         plan.Name,
		PriceUsd:     plan.PriceUSD,
		DataGb:       plan.DataGB,
		ValidityDays: plan.ValidityDays,
		Tradeoff:     plan.Tradeoff,
	}
}

func toGraphPlanOptions(plans []domain.PlanOption) []*models.PlanOption {
	result := make([]*models.PlanOption, 0, len(plans))
	for _, plan := range plans {
		result = append(result, toGraphPlanOption(plan))
	}
	return result
}

func toGraphConnectivityGuide(guide *domain.ConnectivityGuide) *models.ConnectivityGuide {
	if guide == nil {
		return nil
	}
	return &models.ConnectivityGuide{
		BeforeDeparture: guide.BeforeDeparture,
		AirportSetup:    guide.AirportSetup,
		OfflineStrategy: guide.OfflineStrategy,
		BackupInternet:  guide.BackupInternet,
		EmergencyAccess: guide.EmergencyAccess,
	}
}

func toGraphAgentSteps(steps []domain.AgentStep) []*models.AgentStep {
	result := make([]*models.AgentStep, 0, len(steps))
	for _, step := range steps {
		result = append(result, &models.AgentStep{
			Name:          step.Name,
			Status:        models.AgentStatus(step.Status),
			DurationMs:    step.DurationMS,
			InputSummary:  step.InputSummary,
			OutputSummary: step.OutputSummary,
			Retries:       step.Retries,
			Error:         step.Error,
		})
	}
	return result
}
